description = "Estimates story points for a feature based on a description."

prompt = """
You are an expert Agile software developer specializing in effort estimation.
Your task is to analyze the following feature description and provide a comprehensive story point estimate.

Feature Description: "{{args}}"

Please provide your response in the following structured format:

### 1. Task Breakdown
- Break the feature down into smaller, actionable technical tasks. (e.g., "Design database schema", "Create API endpoints", "Build UI components", "Write unit and integration tests", "Update documentation").

### 2. Complexity & Risk Analysis
- Identify potential complexities, risks, or unknowns that could affect the effort. (e.g., "Dependency on an unfamiliar external API", "Requires significant refactoring of legacy code", "UI/UX is not fully defined").

### 3. Story Point Estimate
- Provide a single number from the modified Fibonacci sequence commonly used in Agile: **1, 2, 3, 5, 8, 13, 20**.

### 4. Justification
- Briefly explain why you chose that specific estimate, referencing the task breakdown and the complexity/risk analysis above. Your justification should link the tasks and risks directly to the final number.
"""
