steps:
  # Step to access the Hugging Face token and print it
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Accessing Hugging Face Token..."
        echo "Hugging Face Token: $$HUGGING_FACE_HUB_TOKEN"
    secretEnv: ['HUGGING_FACE_HUB_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/234439745674/secrets/HUGGING_FACE_HUB_TOKEN/versions/1
      env: 'HUGGING_FACE_HUB_TOKEN'

timeout: '1200s'
