steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'artifacts'
      - 'repositories'
      - 'create'
      - 'adk-audio-assistant'
      - '--repository-format=docker'
      - '--location=us-central1'
      - '--description=Repository for ADK Audio Assistant'
      - '--quiet'
    id: 'create-repo'
    allowFailure: true  # Allow failure if repo already exists

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-audio-assistant/audio-assistant:latest', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-audio-assistant/audio-assistant:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'adk-audio-assistant'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/adk-audio-assistant/audio-assistant:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=8765'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--session-affinity'
      - '--set-env-vars=GOOGLE_GENAI_USE_VERTEXAI=TRUE,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/adk-audio-assistant/audio-assistant:latest'
